name:                fasta
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/fasta#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2018 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - attoparsec
  - attoparsec-applicative  
  - base >= 4.7 && < 5
  - bytestring
  - conduit
  - conduit-extra
  
tests:
  fasta-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - fasta

library:
  exposed-modules:
     - Bio.Fasta.Fasta
     - Bio.Fasta.FastaParser
  source-dirs: lib

